# fly.toml app configuration file generated for foromid on 2023-09-29T12:03:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foromid"
primary_region = "eze"
console_command = "/code/manage.py shell"

[build]
  args = { DATABASE_URL = "postgres://usuario:contraseña@host:puerto/nombre_de_base_de_datos" }

[env]
  PORT = "8000"


[[config.env]]
  name = "GOOGLE_APPLICATION_CREDENTIALS"
  value = "/credencials/credencial.json"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

